services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    runtime: python
    region: oregon
    plan: free
envVars:
  - key: PYTHON_VERSION
    value: 3.12.3
